apply from: 'gradle/scripts/helpers.gradle'

//configurations {
//    shade
//}

repositories {
    maven { url 'https://repo.sleeping.town' }

    exclusiveContent {
        forRepository {
            maven {
                name 'CurseMaven'
                url 'https://cursemaven.com'
            }
        }
        filter {
            includeGroup 'curse.maven'
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                name 'Modrinth'
                url 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }

    mavenLocal() // Must be last for caching to work
}

dependencies {
    embed implementation('net.dv8tion:JDA:5.0.0-beta.21') {
        exclude module: 'opus-java'
    }
    embed implementation('folk.sisby:kaleido-config:0.3.1+1.3.1')
}