plugins {
	id 'com.unascribed.nilgradle' version '1.4.4'
	id 'com.github.johnrengelman.shadow' version '7.1.2'
}

sourceCompatibility = 8
targetCompatibility = 8

compileJava.options.encoding = 'UTF-8'

group = 'cc.unilock'
archivesBaseName = 'nilcord'
version = '2.4.3'

repositories {
	mavenLocal()
	maven {
		url 'https://repo.sleeping.town'
		content {
			includeGroup 'com.unascribed'
			includeGroup 'folk.sisby'
		}
	}
	mavenCentral()
}

nil {
	id "nilcord"
	standalone false
}

configurations {
	shade
}

dependencies {
	loader 'com.unascribed:nilloader:1.3.4'

	game nil.minecraft('1.4.7', 'client')

	implementation shade('net.dv8tion:JDA:5.3.2') {
		exclude module: 'opus-java'
	}
	implementation shade('folk.sisby:kaleido-config:0.3.3+1.3.2')
}

mappings {
	work 'com.unascribed:unknownthingy:1.23@tsrg'
}

jar {
	archiveClassifier = 'slim'
}

shadowJar {
	archiveClassifier = ''

	configurations = [project.configurations.shade]

	exclude 'LICENSE'
	exclude 'META-INF/**'
	exclude 'module-info.class'

	relocate 'com.fasterxml.jackson', 'cc.unilock.nilcord.lib.jackson'
	relocate 'com.google.crypto', 'cc.unilock.nilcord.lib.crypto'
	relocate 'com.google.errorprone', 'cc.unilock.nilcord.lib.errorprone'
	relocate 'com.google.gson', 'cc.unilock.nilcord.lib.gson'
	relocate 'com.neovisionaries.ws', 'cc.unilock.nilcord.lib.ws'
	relocate 'folk.sisby.kaleido', 'cc.unilock.nilcord.lib.kaleido'
	relocate 'gnu.trove', 'cc.unilock.nilcord.lib.trove'
	relocate 'google.protobuf', 'cc.unilock.nilcord.lib.protobuf'
	relocate 'javax.annotation', 'cc.unilock.nilcord.lib.annotation'
	relocate 'kotlin', 'cc.unilock.nilcord.lib.kotlin'
	relocate 'net.dv8tion.jda', 'cc.unilock.nilcord.lib.jda'
	relocate 'okhttp3', 'cc.unilock.nilcord.lib.okhttp3'
	relocate 'okio', 'cc.unilock.nilcord.lib.okio'
	relocate 'org.apache.commons', 'cc.unilock.nilcord.lib.commons'
	relocate 'org.intellij.lang.annotations', 'cc.unilock.nilcord.lib.intellij_annotations'
	relocate 'org.jetbrains.annotations', 'cc.unilock.nilcord.lib.jetbrains_annotations'
	relocate 'org.slf4j', 'cc.unilock.nilcord.lib.slf4j'

	minimize()
}

tasks.build.dependsOn tasks.shadowJar
