plugins {
	id 'java-library'
	id 'eclipse'
	id 'idea'
	id 'maven-publish'
	id 'net.neoforged.gradle.userdev' version '7.0.153'
	id 'com.github.johnrengelman.shadow' version '7.1.2'
}

version = "${mod_version}+${minecraft_version}+neoforge"
group = mod_group_id

repositories {
	maven { url 'https://maven.nucleoid.xyz/' }
	maven { url 'https://repo.sleeping.town/' }
	mavenCentral()
}

base {
	archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

runs {
	configureEach {
		systemProperty 'forge.logging.markers', 'REGISTRIES'

		systemProperty 'forge.logging.console.level', 'debug'

		modSource project.sourceSets.main
	}

	client {
		systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
	}

	server {
		systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
		programArgument '--nogui'
	}

	gameTestServer {
		systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
	}

	data {
		programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
	}
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
	runtimeClasspath.extendsFrom localRuntime
	shade
}

dependencies {
	implementation "net.neoforged:neoforge:${neo_version}"

	implementation shade("net.dv8tion:JDA:${project.jda_version}") {
		exclude module: 'opus-java'
	}
	implementation shade("folk.sisby:kaleido-config:${project.kaleido_version}")

	shade("com.fasterxml.jackson.core:jackson-core:2.16.0")
	shade("com.fasterxml.jackson.core:jackson-databind:2.16.0")
	shade("com.fasterxml.jackson.core:jackson-annotations:2.16.0")
	shade("com.neovisionaries:nv-websocket-client:2.14")
	shade("com.squareup.okhttp3:okhttp:4.12.0")
	shade("com.squareup.okio:okio-jvm:3.9.0")
	shade("net.sf.trove4j:trove4j:3.0.3")
	shade("org.apache.commons:commons-collections4:4.4")
	shade("org.jetbrains.kotlin:kotlin-stdlib:1.9.23")
	shade("org.slf4j:slf4j-api:2.0.12") // Use 2.0 instead of 1.0
}

jar {
	archiveClassifier = 'slim'
}

shadowJar {
	archiveClassifier = ''

	configurations = [project.configurations.shade]

	exclude 'LICENSE'
	exclude 'META-INF/**'

	relocate 'com.electronwill.nightconfig', 'cc.unilock.nilcord.lib.nightconfig'
	relocate 'com.fasterxml.jackson', 'cc.unilock.nilcord.lib.jackson'
	relocate 'com.iwebpp.crypto', 'cc.unilock.nilcord.lib.crypto'
	relocate 'com.neovisionaries.ws', 'cc.unilock.nilcord.lib.ws'
	relocate 'folk.sisby.kaleido', 'cc.unilock.nilcord.lib.kaleido'
	relocate 'gnu.trove', 'cc.unilock.nilcord.lib.trove'
	relocate 'kotlin', 'cc.unilock.nilcord.lib.kotlin'
	relocate 'net.dv8tion.jda', 'cc.unilock.nilcord.lib.jda'
	relocate 'okhttp3', 'cc.unilock.nilcord.lib.okhttp3'
	relocate 'okio', 'cc.unilock.nilcord.lib.okio'
	relocate 'org.apache.commons', 'cc.unilock.nilcord.lib.commons'
	relocate 'org.jetbrains.annotations', 'cc.unilock.nilcord.lib.annotations'
	relocate 'org.slf4j', 'cc.unilock.nilcord.lib.slf4j'

	minimize()
}

tasks.build.dependsOn tasks.shadowJar

tasks.withType(ProcessResources).configureEach {
	var replaceProperties = [
			minecraft_version		: minecraft_version,
			minecraft_version_range	: minecraft_version_range,
			neo_version				: neo_version,
			neo_version_range		: neo_version_range,
			loader_version_range	: loader_version_range,
			mod_id					: mod_id,
			mod_name				: mod_name,
			mod_license				: mod_license,
			mod_version				: mod_version,
			mod_authors				: mod_authors,
			mod_description			: mod_description
	]
	inputs.properties replaceProperties

	filesMatching(['META-INF/mods.toml']) {
		expand replaceProperties
	}
}

// Example configuration to allow publishing using the maven-publish plugin
publishing {
	publications {
		register('mavenJava', MavenPublication) {
			from components.java
		}
	}
	repositories {
		maven {
			url "file://${project.projectDir}/repo"
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
	module {
		downloadSources = true
		downloadJavadoc = true
	}
}
