plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

repositories {
    maven {
        name = 'Nucleoid'
        url = 'https://maven.nucleoid.xyz/'
    }
    maven {
        name = 'Sleeping Town'
        url = 'https://repo.sleeping.town/'
    }
}

dependencies {
    // https://github.com/neoforged/NeoForge/blob/26.2.x/gradle.properties#L37
    // https://github.com/FabricMC/fabric-loader/blob/master/gradle.properties#L12
    compileOnly('net.fabricmc:sponge-mixin:0.17.3+mixin.0.8.7')
    compileOnly(annotationProcessor('io.github.llamalad7:mixinextras-common:0.5.3'))

    implementation("folk.sisby:kaleido-config:${kaleido_version}")
    implementation("eu.pb4:placeholder-api:${papi_fabric_version}")

    implementation("net.dv8tion:JDA:${jda_version}") {
        exclude module: 'opus-java'
    }
}

neoForge {
    neoFormVersion = neo_form_version
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
